---
title: "01_orthoFinder-within"
author: "zagor"
date: "`r Sys.Date()`"
output:
  html_document:
    fig_caption: yes
    self_contained: yes
    fig_width: 9
    fig_height: 8
    toc: true
    toc_float:
      toc_collapsed: false
    toc_depth: 5
    number_sections: yes
    theme: flatly
    highlight: tango
  pdf_document:
    toc: yes
    toc_depth: '2'
  word_document:
    toc: yes
    toc_depth: '2'
editor_options:
  chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(dev = c('png', 'pdf'),  # this embeds pdf and crates scrolable blocks if pdf is first
                      fig.path = "../reports/orthoFinder-within/", # save each figure here
                      # dev = c('png'), 
                      fig.align = 'center', 
                      dpi = 300,
                      fig.height = 8, 
                      fig.width = 9 ,
                      warning = FALSE, message = FALSE
                      )
```



```{r,  echo=TRUE, warning=FALSE, message=FALSE}

rm(list = ls(all = TRUE))
gc()


library(magrittr)

setwd(dirname(rstudioapi::getActiveDocumentContext()$path))




```

```{r}

my.func <- function(fpi, fl){
  
  df.p = NULL

  for (i in fl) {
    
    print(i)
  
    df = NULL
    
    df = data.table::fread(file.path(fpi, i))
    source = colnames(df)[3]
    colnames(df)[3] = 'sourceID'
    colnames(df)[2] = 'target'
    
    df.pairs = NULL
    
    df.pairs = df %>%
      dplyr::mutate(
        sourceID = stringr::str_split(sourceID, ",\\s*"),
        Orthologs = stringr::str_split(Orthologs, ",\\s*")
      ) %>%
      dplyr::rowwise() %>%
      dplyr::mutate(pairs = list(tidyr::crossing(ID = sourceID, ortho = Orthologs))) %>%
      tidyr::unnest(pairs) %>%
      dplyr::ungroup() %>%
      dplyr::select(ID, ortho, Orthogroup, target) %>%
      dplyr::rename(sourceID = ID, targetID = ortho)
    
    df.pairs$source = source
    
    df.p = rbind(df.p, df.pairs)
  
  }
  
  df.p = df.p[order(df.p$Orthogroup, df.p$targetID, df.p$sourceID), ]
  return(df.p)

}


```



```{r}

fp = file.path('..', 'input', 'OrthoFinder')

```

# OrthoFinder

```{r}

fpi = file.path(fp, 'ath_arabidopsis')
fl = list.files(fpi)


df.pairs = my.func(fpi, fl)

head(df.pairs)
tail(df.pairs)

table(df.pairs$sourceID == df.pairs$targetID)

df.pairs$source = gsub('_.*', '', df.pairs$source)
df.pairs$target = gsub('_.*', '', df.pairs$target)

table(df.pairs$source, df.pairs$target)

df.pairs$sourceGeneID = sub("\\.[0-9]+$", "", df.pairs$sourceID)
df.pairs$targetGeneID = sub("\\.[0-9]+$", "", df.pairs$targetID)

table(df.pairs$sourceGeneID == df.pairs$targetGeneID)

df.pairs$identicalGeneID = FALSE
df.pairs$identicalGeneID[df.pairs$sourceGeneID == df.pairs$targetGeneID] = TRUE
sum(df.pairs$identicalGeneID)

df.pairs$plant = 'ath'

cols_first = c(
  "sourceID", "sourceGeneID", "source",
  "targetID", "targetGeneID", "target",
  "Orthogroup",	"identicalGeneID",	"plant"
  )

df.pairs = df.pairs[, cols_first]

file_path = "../intermediate/orthofinder_ath-within.txt"
data.table::fwrite(df.pairs, file_path, sep = '\t')
root_dir = dirname(file_path)
file_name = basename(file_path)
zip::zip(zipfile = paste0(file_path, ".zip"), 
    files = file_name, 
    root = root_dir)
file.remove(file_path)

```


# compara

```{r}

table(df.pairs$source)
df.compara = df.pairs[df.pairs$source == 'Compara', ]
cols_first = c(
  "sourceID", 
  "targetID", 
  "target"
  )
df.compara = df.compara[, cols_first]
df_wide = df.compara %>%
  tidyr::pivot_wider(
    names_from = target,
    values_from = targetID,
    values_fn = list(targetID = ~ paste(unique(.), collapse = ", ")), # handle multiple values per sourceID-target
    values_fill = NA
  )


file_path = "../intermediate/orthofinder_ath-within_compara-wide.txt"
data.table::fwrite(df_wide, file_path, sep = '\t')
root_dir = dirname(file_path)
file_name = basename(file_path)
zip::zip(zipfile = paste0(file_path, ".zip"), 
    files = file_name, 
    root = root_dir)
file.remove(file_path)

```

# plaza

```{r}


df.plaza = df.pairs[df.pairs$source == 'PLAZA', ]
cols_first = c(
  "sourceID", 
  "targetID", 
  "target"
  )
df.plaza = df.plaza[, cols_first]
df_wide = df.plaza %>%
  tidyr::pivot_wider(
    names_from = target,
    values_from = targetID,
    values_fn = list(targetID = ~ paste(unique(.), collapse = ", ")), # handle multiple values per sourceID-target
    values_fill = NA
  )


file_path = '../intermediate/orthofinder_ath-within_plaza-wide.txt'
data.table::fwrite(df_wide, file_path, sep = '\t')
root_dir = dirname(file_path)
file_name = basename(file_path)
zip::zip(zipfile = paste0(file_path, ".zip"), 
    files = file_name, 
    root = root_dir)
file.remove(file_path)

```


# OrthoDB

```{r}


df.orthodb = df.pairs[df.pairs$source == 'OrthoDB', ]
cols_first = c(
  "sourceID", 
  "targetID", 
  "target"
  )
df.orthodb = df.orthodb[, cols_first]
df_wide = df.orthodb %>%
  tidyr::pivot_wider(
    names_from = target,
    values_from = targetID,
    values_fn = list(targetID = ~ paste(unique(.), collapse = ", ")), # handle multiple values per sourceID-target
    values_fill = NA
  )


file_path = '../intermediate/orthofinder_ath-within_OrthoDB-wide.txt'
data.table::fwrite(df_wide, file_path, sep = '\t')
root_dir = dirname(file_path)
file_name = basename(file_path)
zip::zip(zipfile = paste0(file_path, ".zip"), 
    files = file_name, 
    root = root_dir)
file.remove(file_path)

```


# e.g. inconsistent multimatch

```{r}

ind = c(grep('AT5G36380', df.pairs$sourceID),
        grep('AT5G36380', df.pairs$targetID))
df.pairs[ind, ]
df.orthodb[df.orthodb$targetID == 'AT5G36380.1', ]
df.orthodb[df.orthodb$targetID == 'AT5G36440.1', ]
df.plaza[df.plaza$sourceID == 'AT5G36380.1', ]
df.plaza[df.plaza$targetID == 'AT5G36380.1', ]
df.compara[df.compara$sourceID == 'AT5G36380.1', ]

```



# sessionInfo

```{r,  echo=TRUE, warning=FALSE, message=FALSE}

sessionInfo()

```




