---
title: "04_FastOMA2"
author: "zagor"
date: "`r Sys.Date()`"
output:
  html_document:
    fig_caption: yes
    self_contained: yes
    fig_width: 9
    fig_height: 8
    toc: true
    toc_float:
      toc_collapsed: false
    toc_depth: 5
    number_sections: yes
    theme: flatly
    highlight: tango
  pdf_document:
    toc: yes
    toc_depth: '2'
  word_document:
    toc: yes
    toc_depth: '2'
editor_options:
  chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(dev = c('png', 'pdf'),  # this embeds pdf and crates scrolable blocks if pdf is first
                      fig.path = "../reports/FastOMA2/", # save each figure here
                      # dev = c('png'), 
                      fig.align = 'center', 
                      dpi = 300,
                      fig.height = 8, 
                      fig.width = 9 ,
                      warning = FALSE, message = FALSE
                      )
```



```{r,  echo=TRUE, warning=FALSE, message=FALSE}

rm(list = ls(all = TRUE))
gc()


library(magrittr)

setwd(dirname(rstudioapi::getActiveDocumentContext()$path))




```

# plant selection

```{r}

fp = file.path('..', 'input', 'FastOMA_plants')
fl = list.files(fp)

myList = NULL

for (i in fl) {
  lines = readLines(file.path(fp, i))
  headers = grep("^>", lines, value = TRUE)
  ids = sub("^>", "", headers)
  ids = sub("\\s.*$", "", ids)
  ids = as.data.frame(ids)
  ids$plant = sub('\\..*', '', i)
  myList = rbind(myList, ids)

}


```

# input

```{r}

fp = file.path('..', 'input', 'FastOMA', 'run4_Pentapetalae')
fn = 'orthologs.tsv.gz'

df = data.table::fread(file.path(fp, fn), header = FALSE)
colnames(df) = c('from', 'to')
colnames(myList) = c('from', 'from_plant')
df = merge(df, myList, by = 'from', all.x = TRUE)
colnames(myList) = c('to', 'to_plant')
df = merge(df, myList, by = 'to', all.x = TRUE)
table(df$from_plant, df$to_plant)

```

# output

```{r}

dt = df[df$from_plant == 'ath' | df$to_plant == 'ath', ]
table(dt$from_plant, dt$to_plant)
columns = c("from", "from_plant", "to", "to_plant")
dt = dt[, ..columns]

dt = dt[!duplicated(dt), ]

dt$source = 'FastOMA'

file_path = '../intermediate/FastOMA2_ath-pairs.txt'
data.table::fwrite(dt, file_path, sep = '\t')
root_dir = dirname(file_path)
file_name = basename(file_path)
zip::zip(zipfile = paste0(file_path, ".zip"), 
    files = file_name, 
    root = root_dir)
file.remove(file_path)

```


# sessionInfo

```{r,  echo=TRUE, warning=FALSE, message=FALSE}

sessionInfo()

```

