---
title: "04_FastOMA"
author: "zagor"
date: "`r Sys.Date()`"
output:
  html_document:
    fig_caption: yes
    self_contained: yes
    fig_width: 9
    fig_height: 8
    toc: true
    toc_float:
      toc_collapsed: false
    toc_depth: 5
    number_sections: yes
    theme: flatly
    highlight: tango
  pdf_document:
    toc: yes
    toc_depth: '2'
  word_document:
    toc: yes
    toc_depth: '2'
editor_options:
  chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(dev = c('png', 'pdf'),  # this embeds pdf and crates scrolable blocks if pdf is first
                      fig.path = "../reports/FastOMA/", # save each figure here
                      # dev = c('png'), 
                      fig.align = 'center', 
                      dpi = 300,
                      fig.height = 8, 
                      fig.width = 9 ,
                      warning = FALSE, message = FALSE
                      )
```



```{r,  echo=TRUE, warning=FALSE, message=FALSE}

rm(list = ls(all = TRUE))
gc()


library(magrittr)
library(data.table)

setwd(dirname(rstudioapi::getActiveDocumentContext()$path))




```


# params

```{r, params}

params_list = list(
  list(to_plant = 'stu', stp = 'stu', # standardised plant abbreviation 
 to_sub_pattern = "(\\.[0-9]+)+$"), # numbers after last dots marking gene: .1 or .1.1 + exception
  list(to_plant = 'sly', stp = 'sly', # standardised plant abbreviation 
       to_sub_pattern = "\\.[0-9]+(\\.p[0-9]+)?$"), # remove everything from the last '.' and also for e.g. .1.p1 in PRAM_106208
  list(to_plant = 'vvi', stp = 'vvi', # standardised plant abbreviation 
       to_sub_pattern = "(_[^_]+){2}$"), # remove everything second from the last '_'
    
  list(to_plant = 'mdo', stp = 'mdo', # standardised plant abbreviation 
       to_sub_pattern = "\\.[^.]*$"), # everythin after the last dot
  list(to_plant = 'pper', stp = 'ppe', # standardised plant abbreviation 
       to_sub_pattern = "\\.[^.]*$"), # everythin after the last dot
  list(to_plant = 'pdul', stp = 'pdul', # standardised plant abbreviation 
       to_sub_pattern = "\\.[^.]*$"), # everythin after the last dot
  list(to_plant = 'pavi', stp = 'pavi', # standardised plant abbreviation 
       to_sub_pattern = "-[^-]*$"), # T1, T2, T3 in .bed file have the same coord
  list(to_plant = 'parm', stp = 'parm', # standardised plant abbreviation 
       to_sub_pattern = "\\.[^.]+\\.[^.]+$"), # .t1.p1_1
  
  list(to_plant = 'pcer', stp = 'pcer', # standardised plant abbreviation 
       to_sub_pattern = "\\.[^.]+\\.[^.]+$"), # .t1.p1_1
  list(to_plant = 'pcox', stp = 'pcox', # standardised plant abbreviation 
       to_sub_pattern = "\\.[^.]*$"), # .t1
   list(to_plant = 'psib', stp = 'psib', # standardised plant abbreviation 
       to_sub_pattern = "\\.[^.]+\\.[^.]+$") # .t1.p1_1
  
)


pattern_map = purrr::map_chr(params_list, "to_sub_pattern") %>%
  setNames(purrr::map_chr(params_list, "to_plant"))
pattern_mapP = purrr::map_chr(params_list, "stp") %>%
  setNames(purrr::map_chr(params_list, "to_plant"))



```

# stu exception

```{r, stu_read}

# unitato DMG-DMT
url = "https://raw.githubusercontent.com/NIB-SI/unitato/main/output/Phureja_v4-v6.1_annotations.xlsx"
temp_file = tempfile(fileext = ".xlsx")
download.file(url, destfile = temp_file, mode = "wb")
DMT2DMG = openxlsx::read.xlsx(temp_file, startRow  = 3)
# head(DMT2DMG)
columns = c('geneID', 'v4_PGSC_DMT')
DMT2DMG = DMT2DMG[, columns]
DMT2DMG = DMT2DMG[!is.na(DMT2DMG$v4_PGSC_DMT), ]
setDT(DMT2DMG)

```


# plant gene IDs

```{r}

fp = file.path('..', 'input', 'FastOMA_plants')
fl = list.files(fp)

myList = NULL

for (i in fl) {
  lines = readLines(file.path(fp, i))
  headers = grep("^>", lines, value = TRUE)
  ids = sub("^>", "", headers)
  ids = sub("\\s.*$", "", ids)
  ids = as.data.frame(ids)
  ids$plant = sub('\\..*', '', i)
  myList = rbind(myList, ids)

}


```

# input

```{r}

fp = file.path('..', 'input', 'FastOMA', 'run4_Pentapetalae')
fn = 'orthologs.tsv.gz'

df = data.table::fread(file.path(fp, fn), header = FALSE)
colnames(df) = c('from', 'to')
colnames(myList) = c('from', 'from_plant')
df = merge(df, myList, by = 'from', all.x = TRUE)
colnames(myList) = c('to', 'to_plant')
df = merge(df, myList, by = 'to', all.x = TRUE)
table(df$from_plant, df$to_plant)

```

# ath-plant pairs

```{r}

dt = df[df$from_plant == 'ath' | df$to_plant == 'ath', ]
table(dt$from_plant, dt$to_plant)
columns = c("from", "from_plant", "to", "to_plant")
dt = dt[, ..columns]

dt = dt[!duplicated(dt), ]

dt$source = 'FastOMA'

dt$from = gsub("\\.[^.]*$", "", dt$from) # remove everything after the last dot in ath

dt %>%
  dplyr::group_by(to_plant) %>%
  dplyr::slice_head(n = 2) %>%
  dplyr::bind_rows(dt %>% dplyr::group_by(to_plant) %>% dplyr::slice_tail(n = 2)) %>%
  dplyr::arrange(to_plant) %>%
  dplyr::ungroup() -> first_last_two_per_plant

print(first_last_two_per_plant, n = nrow(first_last_two_per_plant))


fix_to_by_pattern <- function(to, plant) {
  pattern = pattern_map[plant]
  if (!is.na(pattern)) {
    gsub(pattern, "", to)
  } else {
    to
  }
}

# pattern_map pattern for each to_plant
dt[, to := mapply(fix_to_by_pattern, to, to_plant)]
dt[, to_plant := pattern_mapP[to_plant]]

# potato exception
dt_stu = dt[to_plant == "stu"]
setkey(DMT2DMG, v4_PGSC_DMT)
dt_stu[DMT2DMG, on = .(to = v4_PGSC_DMT), to := i.geneID]
dt[to_plant == "stu", to := dt_stu$to]

dt = dt[!duplicated(dt), ]

dt %>%
  dplyr::group_by(to_plant) %>%
  dplyr::slice_head(n = 2) %>%
  dplyr::bind_rows(dt %>% dplyr::group_by(to_plant) %>% dplyr::slice_tail(n = 2)) %>%
  dplyr::arrange(to_plant) %>%
  dplyr::ungroup() -> first_last_two_per_plant

print(first_last_two_per_plant, n = nrow(first_last_two_per_plant))

```


# write and zip

```{r, zip}

file_path = '../intermediate/FastOMA_cleaned.txt'
data.table::fwrite(dt, file_path, sep = '\t')
root_dir = dirname(file_path)
file_name = basename(file_path)
zip::zip(zipfile = paste0(file_path, ".zip"), 
    files = file_name, 
    root = root_dir)
file.remove(file_path)

```


# sessionInfo

```{r,  echo=TRUE, warning=FALSE, message=FALSE}

sessionInfo()

```

