---
title: "07_RBH"
author: "zagor"
date: "`r Sys.Date()`"
output:
  html_document:
    fig_caption: yes
    self_contained: yes
    fig_width: 9
    fig_height: 8
    toc: true
    toc_float:
      toc_collapsed: false
    toc_depth: 5
    number_sections: yes
    theme: flatly
    highlight: tango
  pdf_document:
    toc: yes
    toc_depth: '2'
  word_document:
    toc: yes
    toc_depth: '2'
editor_options:
  chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(dev = c('png', 'pdf'),  # this embeds pdf and crates scrolable blocks if pdf is first
                      fig.path = "../reports/RBH/", # save each figure here
                      # dev = c('png'), 
                      fig.align = 'center', 
                      dpi = 300,
                      fig.height = 8, 
                      fig.width = 9 ,
                      warning = FALSE, message = FALSE
                      )
```



```{r,  echo=TRUE, warning=FALSE, message=FALSE}

rm(list = ls(all = TRUE))
gc()


library(magrittr)
library(data.table)

setwd(dirname(rstudioapi::getActiveDocumentContext()$path))




```




# fruitdiv

```{r}

process_RBH <- function(input_dir, file_name, from_plant, to_plant, from_sub_pattern, to_sub_pattern) {
  # Read the data
  df = data.table::fread(file.path(input_dir, file_name), header = TRUE)
  
  # Select first two columns, rename to generic
  df_sub = df[, 1:2]
  colnames(df_sub) = c('from', 'to')
  
  # Add metadata columns
  df_sub$from_plant = from_plant
  df_sub$to_plant = to_plant
  df_sub$source = 'RBH'
  
  # Reorder columns
  df_sub = df_sub[, c('from', 'from_plant', 'to', 'to_plant', 'source')]
  
  # Apply substitutions to 'from' and 'to' columns if patterns provided
  if (!missing(from_sub_pattern) && !is.null(from_sub_pattern)) {
    df_sub$from = sub(from_sub_pattern, '', df_sub$from)
  }
  if (!missing(to_sub_pattern) && !is.null(to_sub_pattern)) {
    df_sub$to = sub(to_sub_pattern, '', df_sub$to)
  }
  

  # Return processed data (optional)
  return(df_sub)
}



# Define the list of parameter sets for each plant/file
params_list = list(
  list(file_name = 'ath_mdo.txt', to_plant = 'mdo', to_sub_pattern = "\\.[^.]*$"), # everythin after the last dot
  list(file_name = 'ath_pper.txt', to_plant = 'ppe', to_sub_pattern = "\\.[^.]*$"), # everythin after the last dot
  list(file_name = 'ath_pdul.txt', to_plant = 'pdul', to_sub_pattern = "\\.[^.]*$"), # everythin after the last dot
  list(file_name = 'ath_pavi.txt', to_plant = 'pavi', to_sub_pattern = "-[^-]*$"), # T1, T2, T3 in .bed file have the same coord, eventhough otherwise stated in https://www.sciencedirect.com/science/article/pii/S0254629924003685
  list(file_name = 'ath_parm.txt', to_plant = 'parm', to_sub_pattern = "\\.[^.]+\\.[^.]+$"), # .t1.p1_1
  list(file_name = 'ath_pcox.txt', to_plant = 'pcox', to_sub_pattern = "\\.[^.]*$"), # everythin after the last dot
  list(file_name = 'ath_pcer.txt', to_plant = 'pcer', to_sub_pattern = NULL), # no substitution for 'to' in this case
  list(file_name = 'ath_psib.txt', to_plant = 'psib', to_sub_pattern = "\\.[^.]+\\.[^.]+$") # .01.P01
)

fp = '../input/RBH'
results = vector("list", length(params_list))


for (i in seq_along(params_list)) {
  p = params_list[[i]]
  results[[i]] = process_RBH(
    input_dir = fp,
    file_name = p$file_name,
    from_plant = 'ath',
    to_plant = p$to_plant,
    from_sub_pattern = "\\.[0-9]+.*$",
    to_sub_pattern = p$to_sub_pattern
  )
}


combined_results = rbindlist(results, use.names = TRUE, fill = TRUE)
combined_results = combined_results[!duplicated(combined_results), ]
table(combined_results$to_plant)


file_path = '../intermediate/RBH_fruitTrees.txt'
data.table::fwrite(combined_results, file_path, sep = '\t')
root_dir = dirname(file_path)
file_name = basename(file_path)
zip::zip(zipfile = paste0(file_path, ".zip"), 
    files = file_name, 
    root = root_dir)
file.remove(file_path)


```



# sessionInfo

```{r,  echo=TRUE, warning=FALSE, message=FALSE}

sessionInfo()

```


