---
title: "08_Mercator7MapMan4"
author: "zagor"
date: "`r Sys.Date()`"
output:
  html_document:
    fig_caption: yes
    self_contained: yes
    fig_width: 9
    fig_height: 8
    toc: true
    toc_float:
      toc_collapsed: false
    toc_depth: 5
    number_sections: yes
    theme: flatly
    highlight: tango
  pdf_document:
    toc: yes
    toc_depth: '2'
  word_document:
    toc: yes
    toc_depth: '2'
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(dev = c('png', 'pdf'),  # this embeds pdf and crates scrolable blocks if pdf is first
                      fig.path = "../reports/compara/", # save each figure here
                      # dev = c('png'), 
                      fig.align = 'center', 
                      dpi = 300,
                      fig.height = 8, 
                      fig.width = 9 ,
                      warning = FALSE, message = FALSE
                      )
```



```{r,  echo=TRUE, warning=FALSE, message=FALSE}

rm(list = ls(all = TRUE))
gc()


library(magrittr)
library(data.table)

`%nin%` = Negate(`%in%`)


setwd(dirname(rstudioapi::getActiveDocumentContext()$path))




```


# stu exception

```{r, stu_read}

# unitato DMG-DMT
url = "https://raw.githubusercontent.com/NIB-SI/unitato/main/output/Phureja_v4-v6.1_annotations.xlsx"
temp_file = tempfile(fileext = ".xlsx")
download.file(url, destfile = temp_file, mode = "wb")
DMT2DMG = openxlsx::read.xlsx(temp_file, startRow  = 3)
# head(DMT2DMG)
columns = c('geneID', 'v4_PGSC_DMT')
DMT2DMG = DMT2DMG[, columns]
DMT2DMG = DMT2DMG[!is.na(DMT2DMG$v4_PGSC_DMT), ]
setDT(DMT2DMG)


```

# params

_Denote_: Mercator meesed up nomenclature

```{r, params}

params_list = list(
  list(plantName = 'mdo'
       , mercator = 'mdo_Mercator4v7_results.txt'
       , mercatorPatternIn1 = "a.g"
       , mercatorPatternOut1 = "A.g"
       , mercatorPatternIn2 = "\\.[^.]*$"
       , mercatorPatternOut2 = ""
       ),
  list(plantName = 'ppe'
       , mercator = 'pper_Mercator4v7_results.txt'
       , mercatorPatternIn1 = "g"
       , mercatorPatternOut1 = "G" 
       , mercatorPatternIn2 = "\\.[^.]*$"
       , mercatorPatternOut2 = ""
       ),
  list(plantName = 'pdul'
       , mercator = 'pdul_Mercator4v7_results.txt'
       , mercatorPatternIn1 = "([fg])"
       , mercatorPatternOut1 = "\\U\\1"
       , mercatorPatternIn2 = "\\.[^.]*$"
       , mercatorPatternOut2 = ""
       ),
  list(plantName = 'pavi'
       , mercator = 'pavi_Mercator4v7_results.txt'
       , mercatorPatternIn1 = "Fun"
       , mercatorPatternOut1 = "FUN" 
       , mercatorPatternIn2 = "-[^-]*$"
       , mercatorPatternOut2 = "" 
       ),
  list(plantName = 'parm'
       , mercator = 'parm_Mercator4v7_results.txt'
       , mercatorPatternIn1 = "([mg])"
       , mercatorPatternOut1 = "\\U\\1" 
       , mercatorPatternIn2 = "^(([^.]*\\.){1}[^.]*)\\..*$"
       , mercatorPatternOut2 = "\\1"
       ),
  list(plantName = 'pcox'
       , mercator = 'pcox_Mercator4v7_results.txt'
       , mercatorPatternIn1 = "(\\.chr\\d+)a(\\.)"
       , mercatorPatternOut1 = "\\1A\\2"
       , mercatorPatternIn2 = "\\.[^.]*$"
       , mercatorPatternOut2 = ""
       ),
  list(plantName = 'pcer'
       , mercator = 'pcer_Mercator4v7_results.txt'
       , mercatorPatternIn1 = "-(ra)"
       , mercatorPatternOut1 = "-\\U\\1"
       , mercatorPatternIn2 = ""
       , mercatorPatternOut2 = ""
       ),
  list(plantName = 'psib'
       , mercator = 'psib_Mercator4v7_results.txt'
       , mercatorPatternIn1= "f106g"
       , mercatorPatternOut1 = "F106G"
       , mercatorPatternIn2 = "(\\.[^.]+){2}$"
       , mercatorPatternOut2 = ""
       ),
  list(plantName = 'ath'
       , mercator = 'ath_Mercator4v7_results.txt'
       , mercatorPatternIn1 = "([tg])"
       , mercatorPatternOut1 = "\\U\\1"
       , mercatorPatternIn2 = "\\.[^.]*$"
       , mercatorPatternOut2 = ""
       ),
  list(plantName = 'stu'
       , mercator = 'stu_Mercator4v7_results.txt'
       , mercatorPatternIn1 = "(\\.[0-9]+)+$"
       , mercatorPatternOut1 = ""
       , mercatorPatternIn2 = "(\\.)(dm)(\\.[0-9]+)(g)"
       , mercatorPatternOut2 = "\\1DM\\3G"
       ),
  list(plantName = 'sly'
       , mercator = 'sly_Mercator4v7_results.txt'
       , mercatorPatternIn1 = "([t])"
       , mercatorPatternOut1 = "\\U\\1"
       , mercatorPatternIn2 = "\\.[^.]*$"
       , mercatorPatternOut2 = ""
       ),
  list(plantName = 'vvi'
       , mercator = 'vvi_Mercator4v7_results.txt'
       , mercatorPatternIn1 = "^(([^_]*_){1}[^_]*)_.*$"
       , mercatorPatternOut1 = "\\1"
       , mercatorPatternIn2 = ""
       , mercatorPatternOut2 = ""
       )
)

plant_names = sapply(params_list, `[[`, "plantName")
plant_files= sapply(params_list, `[[`, "mercator")

```

# normalize IDs

```{r, files}

fp = file.path('..', 'input', 'Mercator')

process_param <- function(param) {
  
  # Extract parameters
  fn = param$mercator
  plant = param$plantName
  print(plant)
  mercatorPatternIn1 = param$mercatorPatternIn1
  mercatorPatternOut1 = param$mercatorPatternOut1
  mercatorPatternIn2 = param$mercatorPatternIn2
  mercatorPatternOut2 = param$mercatorPatternOut2
  
  # Read and clean file
  gmm = data.table::fread(file.path(fp, fn), header = TRUE, fill = TRUE)
  char_cols = names(gmm)[sapply(gmm, is.character)]
  gmm[, (char_cols) := lapply(.SD, function(x) gsub("[\"']", "", x)), .SDcols = char_cols]
  
  # Normalize IDENTIFIER
  gmm$IDENTIFIER = paste0(toupper(substring(gmm$IDENTIFIER, 1, 1)), substring(gmm$IDENTIFIER, 2))
  gmm$IDENTIFIER = gsub(mercatorPatternIn1, mercatorPatternOut1, gmm$IDENTIFIER, perl = TRUE)
  gmm$IDENTIFIER = gsub(mercatorPatternIn2, mercatorPatternOut2, gmm$IDENTIFIER, perl = TRUE)
  
  if (plant == 'stu') {
    ind = grep("dmt", gmm$IDENTIFIER)
    gmm$IDENTIFIER[ind] = toupper(gmm$IDENTIFIER[ind])
    gmm[DMT2DMG, on = .(IDENTIFIER = v4_PGSC_DMT), IDENTIFIER := geneID]
    
  }
  

  
  # Collapse rows by IDENTIFIER
  combined = gmm[, .(
    BINCODE = paste(unique(BINCODE), collapse = " | "),
    NAME = paste(unique(NAME), collapse = " | "),
    DESCRIPTION = paste(unique(DESCRIPTION), collapse = " | ")
  ), by = IDENTIFIER]
  
  # Filter and finalize
  combined = combined[IDENTIFIER != ""]
  combined$plant = plant
  unique(combined)
}


results = lapply(params_list, process_param)
mercator = data.table::rbindlist(results)
rm(results)

mercator$source = 'Mercator'

mercator %>%
  dplyr::group_by(plant) %>%
  dplyr::slice_head(n = 2) %>%
  dplyr::bind_rows(mercator %>% dplyr::group_by(plant) %>% dplyr::slice_tail(n = 2)) %>%
  dplyr::arrange(plant) %>%
  dplyr::ungroup() -> first_last_two_per_plant
print(first_last_two_per_plant, n = nrow(first_last_two_per_plant))


```


# write and zip

```{r, zip}

file_path = '../intermediate/mercator_cleaned.txt'
data.table::fwrite(mercator, file_path, sep = '\t')
root_dir = dirname(file_path)
file_name = basename(file_path)
zip::zip(zipfile = paste0(file_path, ".zip"), 
    files = file_name, 
    root = root_dir)
file.remove(file_path)

```




# sessionInfo

```{r,  echo=TRUE, warning=FALSE, message=FALSE}

sessionInfo()

```



